"""
Test 5 — Auditability
=====================
Runs a set of scenarios through the governed pipeline, then renders the
tamper-evident audit ledger into a human-readable Markdown report.

For every governed decision the report shows:
    • Agent involved        (the four voters + which agents produced each signal)
    • Decision taken        (each agent's APPROVE/REJECT, and the recommended crop)
    • Confidence            (ML probability + the LLM's stated confidence level)
    • Consensus result      (trust-weighted score → APPROVE/REJECT)
    • Final outcome         (ALLOW / BLOCK and the surfaced crop)
    • Supporting evidence   (weather, market, ML top-3, RAG excerpt, trust, hash)

The report is generated FROM the hash-chained ledger (governance/state/audit_ledger.jsonl),
and the chain is re-verified, so the report is provably consistent with the
recorded decisions.

Run:  python governance/generate_audit_report.py
Output: docs/AUDIT_REPORT.md
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from dotenv import load_dotenv
load_dotenv()

from governance.governed_orchestrator import run_governed                     # noqa: E402
from governance.pv_coordination import (AUDIT_LEDGER_PATH, TRUST_STATE_PATH,   # noqa: E402
                                        verify_audit_chain, VOTERS)

REPORT_PATH = os.path.join(os.path.dirname(__file__), "..", "docs", "AUDIT_REPORT.md")

SCENARIOS = [
    ("Mumbai — humid coastal (valid)",
     dict(N=90, P=42, K=43, temperature=24, humidity=80, ph=6.5, rainfall=1500), "Mumbai"),
    ("Bengaluru — high-NPK neutral (valid)",
     dict(N=120, P=80, K=70, temperature=25, humidity=60, ph=7.0, rainfall=1200), "Bengaluru"),
    ("Delhi — extreme pH, depleted soil (invalid)",
     dict(N=2, P=3, K=4, temperature=25, humidity=50, ph=13.0, rainfall=40), "Delhi"),
    ("Jaipur — very low rainfall (invalid)",
     dict(N=20, P=20, K=20, temperature=30, humidity=60, ph=6.0, rainfall=30), "Jaipur"),
]


def render(records: list[dict], chain_ok: bool) -> str:
    L = []
    L.append("# AgroAgent — Governance Audit Report")
    L.append("")
    L.append("_Auto-generated by [governance/generate_audit_report.py]"
             "(../governance/generate_audit_report.py) from the tamper-evident "
             "audit ledger (`governance/state/audit_ledger.jsonl`)._")
    L.append("")
    L.append(f"- **Decisions recorded:** {len(records)}")
    L.append(f"- **Audit-chain integrity:** {'✅ VERIFIED (unbroken SHA-256 chain)' if chain_ok else '❌ BROKEN — ledger tampered'}")
    L.append(f"- **Ledger:** `{os.path.relpath(AUDIT_LEDGER_PATH)}`  |  "
             f"**Trust state:** `{os.path.relpath(TRUST_STATE_PATH)}`")
    L.append("")

    # ---- summary table ----
    L.append("## Summary")
    L.append("")
    L.append("| # | Decision | Recommended | ML conf. | Consensus | Final outcome | Audit hash |")
    L.append("|---|----------|-------------|---------:|-----------|---------------|------------|")
    for i, r in enumerate(records, 1):
        p = r["payload"]
        ev = p.get("evidence", {})
        L.append(f"| {i} | {r['label']} | {p['recommended_crop']} | "
                 f"{ev.get('ml_confidence', 0)*100:.0f}% | "
                 f"{p['consensus']} ({p['weighted_consensus']['score']*100:.0f}%) | "
                 f"**{p['final_status']}** | `{r['entry_hash'][:12]}…` |")
    L.append("")

    # ---- per-decision detail ----
    L.append("## Decision details")
    for i, r in enumerate(records, 1):
        p = r["payload"]
        ev = p.get("evidence", {})
        w = ev.get("weather", {})
        mk = ev.get("market", {})
        L.append("")
        L.append(f"### {i}. {r['label']}")
        L.append("")
        L.append(f"- **Final outcome:** **{p['final_status']}** → "
                 f"`{p['recommended_crop'] if p['final_status']=='ALLOW' else 'Withheld — needs review'}`")
        L.append(f"- **Recommended crop (pipeline):** {p['recommended_crop']}")
        L.append(f"- **Confidence:** ML {ev.get('ml_confidence',0)*100:.0f}% "
                 f"(top-3: {', '.join(f'{c} {s*100:.0f}%' for c,s in ev.get('ml_top_crops',[]))}) "
                 f"· LLM stated: {ev.get('llm_confidence_level','—')}")
        L.append(f"- **Consensus result:** {p['consensus']} — trust-weighted score "
                 f"{p['weighted_consensus']['score']*100:.0f}% "
                 f"(threshold {p['threshold']}, total trust {p['weighted_consensus']['total_weight']})")
        L.append(f"- **Policy gate:** {'PASS' if p['policy_pass'] else 'FAIL'} — {p['policy_reason']}")
        L.append("")
        L.append("**Agents involved & decisions taken:**")
        L.append("")
        L.append("| Agent | Decision | Trust (in→out) | Reason / evidence |")
        L.append("|-------|----------|----------------|-------------------|")
        for v in p["votes"]:
            a = v["agent_id"]
            ti, to = p["trust_in"].get(a, 1.0), p["trust_out"].get(a, 1.0)
            drift = " _(drift-ignored)_" if v["context"].get("drift") else ""
            L.append(f"| {a} | {v['decision']}{drift} | {ti:.3f}→{to:.3f} | {v['reason']} |")
        rejected = [v["agent_id"] for v in p["votes"] if v["decision"] == "REJECT"]
        L.append("")
        L.append(f"- **Rejected by:** {', '.join(rejected) if rejected else 'none'}")
        L.append("")
        L.append("**Supporting evidence:**")
        L.append(f"- Weather: {w.get('suitability','—')} "
                 f"({w.get('temperature','?')}°C / {w.get('humidity','?')}%, source: {w.get('source','?')})")
        L.append(f"- Market: best = {mk.get('best_crop','—')}, "
                 f"profitability score of recommended = {mk.get('score','—')}")
        L.append(f"- Validation: {ev.get('validation_status','—')} "
                 f"(LLM: {ev.get('llm_model','—')})")
        if ev.get("rag_excerpt"):
            L.append(f"- Knowledge-base excerpt: _{ev['rag_excerpt'][:200].strip()}…_")
        L.append(f"- **Audit:** entry `{r['entry_hash'][:16]}…` ← prev `{r['prev_hash'][:12]}…` "
                 f"· trust snapshot `{p.get('trust_snapshot_hash','')[:12]}…` · {r['timestamp']}")
    L.append("")
    L.append("---")
    L.append("")
    L.append("### How to verify this report")
    L.append("")
    L.append("Each entry's hash is `SHA-256(prev_hash + payload)`. Re-run "
             "`python -c \"import sys;sys.path.insert(0,'.');"
             "from governance.pv_coordination import verify_audit_chain as v;print(v())\"` "
             "to confirm the chain is unbroken; editing any past entry flips it to `False`.")
    L.append("")
    return "\n".join(L)


def main():
    # Fresh ledger + trust so the report is self-contained.
    for path in (AUDIT_LEDGER_PATH, TRUST_STATE_PATH):
        if os.path.exists(path):
            os.remove(path)

    print("Running scenarios to populate the audit ledger (live)...")
    labels = []
    for label, soil, loc in SCENARIOS:
        run_governed(soil, location=loc)
        labels.append(label)
        print(f"  • {label}")

    # Read back the hash-chained ledger (source of truth)
    records = []
    with open(AUDIT_LEDGER_PATH) as f:
        for line, label in zip([l for l in f if l.strip()], labels):
            rec = json.loads(line)
            rec["label"] = label
            records.append(rec)

    chain_ok = verify_audit_chain()
    md = render(records, chain_ok)
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        f.write(md)
    print(f"\nAudit-chain verified: {chain_ok}")
    print(f"Report written to {os.path.relpath(REPORT_PATH)} ({len(records)} decisions)")


if __name__ == "__main__":
    main()
